name:  algolia searchDoc

on: deployment
  # push:
  #   branches:
  #     - main
# jobs:
#   algolia:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Get the content of docsearch.json as config
#         id: algolia_config
#         run: echo "::set-output name=config::$(cat docsearch.json | jq -r tostring)"

#       - name: Run algolia/docsearch-scraper image
#         env:
#           ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
#           ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
#           CONFIG: ${{ steps.algolia_config.outputs.config }}
#         run: |
#           docker run \
#             --env APPLICATION_ID=${ALGOLIA_APP_ID} \
#             --env API_KEY=${ALGOLIA_API_KEY} \
#             --env "CONFIG=${CONFIG}" \
#             algolia/docsearch-scraper

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # 获取代码 Checkout
        uses: actions/checkout@v2
      - name: Upload Records
        # 使用 Action
        uses: iChochy/Algolia-Upload-Records@main
        # 设置环境变量
        env:
          APPLICATION_ID: ${{secrets.APPLICATION_ID}}
          ADMIN_API_KEY: ${{secrets.ADMIN_API_KEY}}
          INDEX_NAME: ${{secrets.INDEX_NAME}}
          FILE_PATH: ${{secrets.FILE_PATH}}
